DISABLE_MAGIC_FUNCTIONS=true # disable magic functions
fpath=(~/.zsh/completion $fpath) # add custom completions
setopt histignorespace # ignore commands that start with a space
set -o vi
bindkey '^H' backward-kill-word # Ctrl + Backspace (delete word)
bindkey -e # use emacs keybindings

# history setup
setopt SHARE_HISTORY
HISTFILE=$HOME/.zhistory
SAVEHIST=1000
HISTSIZE=999
setopt HIST_EXPIRE_DUPS_FIRST
bindkey '^[OA' history-search-backward
bindkey '^[OB' history-search-forward

eval "$(fasd --init auto)" # init fasd

alias ls="eza -l --group-directories-first -s type --git"
alias r='cd $(git rev-parse --show-toplevel)' # go to git root
alias g='git'
alias k='kubectl'
alias cat='bat'
alias rg="rg --hidden"
alias yt="youtube-dl"

# fd is fdfind in linux `apt install fd-find`
if [[ `uname` == "Linux" ]]; then
  alias fd='fdfind'
fi

# make dir and enter it
function mkc() {
  mkdir -p "$@" && cd "$@"
}

# fasd & fzf change directory - jump using `fasd` if given argument, filter output of `fasd` using `fzf` else
function z() {
  local dir
  dir="$(fasd -Rdl "$1" | fzf -1 -0 --no-sort +m)" && cd "${dir}" || return 1
}

export MANPATH="/usr/local/man:$MANPATH"
export EDITOR=$(which nvim)
export DOCKER_BUILDKIT=1
export GOPATH=$HOME/go
export FZF_DEFAULT_COMMAND="fd --type d"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export GPG_TTY=$(tty)
export PATH=$PATH:/usr/local/go/bin # ubuntu go installation
export PATH=$PATH:~/.local/bin # windows custom bin path
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/n/bin:$PATH"
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
export PATH=$PATH:/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
export PATH="/usr/local/Cellar/gnu-getopt/1.1.6/bin":$PATH # Use gnu getopts
export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH # nix HOME MANAGER
export DIRENV_LOG_FORMAT="" # disable direnv logging

[[ -e ~/.ssh/github_rsa ]] && ssh-add ~/.ssh/github_rsa # automatically add non default ssh keys

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        source "$BASE16_SHELL/profile_helper.sh"

[[ -f ~/.dotfiles/secrets/env ]] && source ~/.dotfiles/secrets/env

# NIX HOME MANAGER
source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"

if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then . $HOME/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
eval "$(direnv hook zsh)"

# tmux ssh session
if [[ -n "$PS1" ]] && [[ -z "$TMUX" ]] && [[ -n "$SSH_CONNECTION" ]]; then
  tmux attach-session -t ssh_tmux || tmux new-session -s ssh_tmux
fi

# This has to be at the bottom for it to work need to figure out what is
# overriding this if i put it in the start of the file
bindkey '^[[1;2D' backward-word # Shift + Left Arrow (move word left)
bindkey '^[[1;2C' forward-word # Shift + Right Arrow (move word right)
