-- Set Telescope colors
-- TODO: This should be moved next to telescope setup but for some reason it
-- doesn't work there
-- local bg = require("base16-colorscheme").colors.base00
-- local fg = require("base16-colorscheme").colors.base04
-- vim.cmd("highlight TelescopePromptTitle guibg=" .. bg .. " guifg=" .. fg)
-- vim.cmd("highlight TelescopePreviewTitle guibg=" .. bg .. " guifg=" .. fg)
-- vim.cmd("highlight TelescopeResultsTitle guibg=" .. bg .. " guifg=" .. fg)
-- vim.cmd("highlight TelescopeBorder guifg=" .. fg)
-- vim.cmd("highlight TelescopePromptBorder guifg=" .. fg .. " guibg=" .. bg)
